version: 0.2

phases:
  install:
    commands:
      - n 16
  build:
    commands:
      - npm install
      - > 
        echo "{\"foo\"\: \"${CODEBUILD_RESOLVED_SOURCE_VERSION}\"}" > ./src/config/githash.json
      - npm run build
      - aws run deploy
