version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm install
      - echo "{\"foo\": \"${CODEBUILD_RESOLVED_SOURCE_VERSION}\"}" > ./src/config/githash.json"
  build:
    commands:
      - npm run build
      - aws run deploy
